// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: app/protobuf/rpc/promotion.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	message "promotion-service/protogen/message"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PromotionService_GetPromotionById_FullMethodName        = "/promotion.rpc.PromotionService/GetPromotionById"
	PromotionService_CreatePromotion_FullMethodName         = "/promotion.rpc.PromotionService/CreatePromotion"
	PromotionService_UpdatePromotion_FullMethodName         = "/promotion.rpc.PromotionService/UpdatePromotion"
	PromotionService_GetPromotionsPagination_FullMethodName = "/promotion.rpc.PromotionService/GetPromotionsPagination"
)

// PromotionServiceClient is the client API for PromotionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromotionServiceClient interface {
	GetPromotionById(ctx context.Context, in *message.GetPromotionByIdRequest, opts ...grpc.CallOption) (*message.GetPromotionByIdResponse, error)
	CreatePromotion(ctx context.Context, in *message.CreatePromotionRequest, opts ...grpc.CallOption) (*message.CreatePromotionResponse, error)
	UpdatePromotion(ctx context.Context, in *message.UpdatePromotionRequest, opts ...grpc.CallOption) (*message.UpdatePromotionResponse, error)
	GetPromotionsPagination(ctx context.Context, in *message.GetPromotionsPaginationRequest, opts ...grpc.CallOption) (*message.GetPromotionsPaginationResponse, error)
}

type promotionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromotionServiceClient(cc grpc.ClientConnInterface) PromotionServiceClient {
	return &promotionServiceClient{cc}
}

func (c *promotionServiceClient) GetPromotionById(ctx context.Context, in *message.GetPromotionByIdRequest, opts ...grpc.CallOption) (*message.GetPromotionByIdResponse, error) {
	out := new(message.GetPromotionByIdResponse)
	err := c.cc.Invoke(ctx, PromotionService_GetPromotionById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) CreatePromotion(ctx context.Context, in *message.CreatePromotionRequest, opts ...grpc.CallOption) (*message.CreatePromotionResponse, error) {
	out := new(message.CreatePromotionResponse)
	err := c.cc.Invoke(ctx, PromotionService_CreatePromotion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) UpdatePromotion(ctx context.Context, in *message.UpdatePromotionRequest, opts ...grpc.CallOption) (*message.UpdatePromotionResponse, error) {
	out := new(message.UpdatePromotionResponse)
	err := c.cc.Invoke(ctx, PromotionService_UpdatePromotion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) GetPromotionsPagination(ctx context.Context, in *message.GetPromotionsPaginationRequest, opts ...grpc.CallOption) (*message.GetPromotionsPaginationResponse, error) {
	out := new(message.GetPromotionsPaginationResponse)
	err := c.cc.Invoke(ctx, PromotionService_GetPromotionsPagination_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromotionServiceServer is the server API for PromotionService service.
// All implementations must embed UnimplementedPromotionServiceServer
// for forward compatibility
type PromotionServiceServer interface {
	GetPromotionById(context.Context, *message.GetPromotionByIdRequest) (*message.GetPromotionByIdResponse, error)
	CreatePromotion(context.Context, *message.CreatePromotionRequest) (*message.CreatePromotionResponse, error)
	UpdatePromotion(context.Context, *message.UpdatePromotionRequest) (*message.UpdatePromotionResponse, error)
	GetPromotionsPagination(context.Context, *message.GetPromotionsPaginationRequest) (*message.GetPromotionsPaginationResponse, error)
	mustEmbedUnimplementedPromotionServiceServer()
}

// UnimplementedPromotionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPromotionServiceServer struct {
}

func (UnimplementedPromotionServiceServer) GetPromotionById(context.Context, *message.GetPromotionByIdRequest) (*message.GetPromotionByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromotionById not implemented")
}
func (UnimplementedPromotionServiceServer) CreatePromotion(context.Context, *message.CreatePromotionRequest) (*message.CreatePromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePromotion not implemented")
}
func (UnimplementedPromotionServiceServer) UpdatePromotion(context.Context, *message.UpdatePromotionRequest) (*message.UpdatePromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePromotion not implemented")
}
func (UnimplementedPromotionServiceServer) GetPromotionsPagination(context.Context, *message.GetPromotionsPaginationRequest) (*message.GetPromotionsPaginationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromotionsPagination not implemented")
}
func (UnimplementedPromotionServiceServer) mustEmbedUnimplementedPromotionServiceServer() {}

// UnsafePromotionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromotionServiceServer will
// result in compilation errors.
type UnsafePromotionServiceServer interface {
	mustEmbedUnimplementedPromotionServiceServer()
}

func RegisterPromotionServiceServer(s grpc.ServiceRegistrar, srv PromotionServiceServer) {
	s.RegisterService(&PromotionService_ServiceDesc, srv)
}

func _PromotionService_GetPromotionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(message.GetPromotionByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).GetPromotionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_GetPromotionById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).GetPromotionById(ctx, req.(*message.GetPromotionByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_CreatePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(message.CreatePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).CreatePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_CreatePromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).CreatePromotion(ctx, req.(*message.CreatePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_UpdatePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(message.UpdatePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).UpdatePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_UpdatePromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).UpdatePromotion(ctx, req.(*message.UpdatePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_GetPromotionsPagination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(message.GetPromotionsPaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).GetPromotionsPagination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_GetPromotionsPagination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).GetPromotionsPagination(ctx, req.(*message.GetPromotionsPaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromotionService_ServiceDesc is the grpc.ServiceDesc for PromotionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromotionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "promotion.rpc.PromotionService",
	HandlerType: (*PromotionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPromotionById",
			Handler:    _PromotionService_GetPromotionById_Handler,
		},
		{
			MethodName: "CreatePromotion",
			Handler:    _PromotionService_CreatePromotion_Handler,
		},
		{
			MethodName: "UpdatePromotion",
			Handler:    _PromotionService_UpdatePromotion_Handler,
		},
		{
			MethodName: "GetPromotionsPagination",
			Handler:    _PromotionService_GetPromotionsPagination_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/protobuf/rpc/promotion.proto",
}
