server:
  port: 8080

database:
  driverName: postgres
  host: localhost
  port: 5432
  userName: postgres
  password: root
  dbName: orders
  sslMode: disable
  maxOpenConnections: 10
  maxIdleConnections: 10
  maxConnLifetime: 10s
  maxConnIdleTime: 10s
