# version: "3.1"

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=orders
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    ports:
      - 5432:5432
    user: root
    networks:
      - local-db-dev-01

networks:
  local-db-dev-01:
    driver: bridge
